### ISSUE TITLE
Provide a sample docker-compose file that includes launching a glauth server?

### ISSUE THREAD

**Issue by traverseda** [sonicnkt/glauth-ui#1]
This is the one I came up with

```yaml
version: '3.7'
services:
  ui:
    image: glauthui:latest
    container_name: glauthui
    restart: unless-stopped
    ports:
      - 801:5000
    volumes:
      # Mount Folder that contains DB and config file outside the container
      - 'glauth:/home/ldap/db'
    environment:
      - SECRET_KEY=mysuperlongsecretkeythatnobodywillguess
      # MAIL CONFIG
      #- MAIL_SERVER=mail.example.com
      #- MAIL_PORT=587
      #- MAIL_USE_TLS=1
      #- MAIL_USERNAME=username
      #- MAIL_PASSWORD=password
      #- MAIL_ADMIN=admin@example.com
  glauth:
    image: glauth/glauth
    command: glauth -c /config/

volumes:
  glauth:
```

Should make it easier for people to get set up. I'm not sure I have it set up properly though.
